service: serverless-api

provider:
  name: aws
  stage: dev
  region: eu-central-1

functions:
  hello:
    handler: js.handler.hello
    runtime: nodejs8.10
    events:
      - http:
          path: js-endpoint
          method: GET

  helloOld:
    handler: js.handler.helloOld
    runtime: nodejs8.10
    events:
      - http:
          path: second/endpoint
          method: GET

  helloPy:
    handler: handler.hello
    runtime: python3.7
    events:
      - http:
          path: py-endpoint
          method: GET

