service: serverless-api

provider:
  name: aws
  stage: dev
  region: eu-central-1

functions:
  hello:
    runtime: python3.7
    events:
      - http:
          method: get
          path: greet
    handler: web/handler.hello

  time:
    runtime: nodejs6.10
    events:
      - http:
          method: get
          path: time
    handler: api/handler.timestamp

